### ISSUE TITLE
Is it expected that Components should appear in search results in some cases?

### ISSUE THREAD

**Issue by corylown** [duke-libraries/ddr-public#144]
@coblej @dchandekstark I recall that one of you made a change that limits search results to Collections and Items (to exclude Components). This seems to work for the most part, but there are a couple of cases where Components still appear in results.

Such as when issuing a blank search from the home page:

https://repository-dev.lib.duke.edu/?utf8=%E2%9C%93&search_field=all_fields&q=

I've also seen this when I try adding an additional field (such as MEDIA_MAJOR_TYPE) to the list of facet fields in blacklight_config in the catalog controller. Selecting one of the facets for MEDIA_MAJOR_TYPE (not currently implemented) also returns Component results.

I'm wondering whether this is by design? Is there a way to prevent Components from appearing as results in these cases? Perhaps you could point out what code changes were made to limit results to Items and Collections so I can better understand this behavior.

Thanks!

Cory

**Comment by dchandekstark** [comment]
We may simply need to add a filter to `CatalogController.solr_search_params_logic` which applies a filter query to exclude Components.  We might also add this topic to the project team meeting agenda.

**Comment by coblej** [comment]
I'm not sure exactly what David has in mind vis-a-vis a filter for `CatalogController.solr_search_params_logic` but this may be a somewhat complicated issue.  E.g., filtering out Components from a MEDIA_MAJOR_TYPE facet will probably result in nothing being displayed because MEDIA_MAJOR_TYPE is (as best I recall) indexed only on Component objects (and Attachment and Target objects, but those aren't currently an issue for the public interface).  I agree with David that this will be a good topic for the project team meeting.

And, to the question about how Components are currently excluded from some but not all search results, they are implicitly excluded only when selecting the Collection and/or Collection Group facet and that is because those facet fields are not indexed on Component objects.

If the end goal is exclude to Component objects from all search results in the public interface (which may well be a good idea), then the solution is probably a combination of the filter David suggests and moving or copying certain index fields from Components to the Items to which they belong.

**Comment by dchandekstark** [comment]
FWIW, the filter I mentioned could look like 

```ruby
  def exclude_components(solr_parameters, user_parameters)
      solr_parameters[:fq] ||= []
      solr_parameters[:fq] << "-#{Ddr::IndexFields::ACTIVE_FEDORA_MODEL}:Component"
  end
```

**Comment by dchandekstark** [comment]
Also, at one time there was an `exclude_unwanted_models` setting that applied a filter like the one above, but we removed that setting as unused.  I suppose we could bring it back ...

**Comment by corylown** [comment]
Thank you! This makes more sense to me now. I will add this topic to our agenda for Monday.
