### ISSUE TITLE
Text for home page

### ISSUE THREAD

**Issue by coblej** [duke-libraries/ddr-public#38]
Provide text for home in override of app/views/catalog/_home_text.html.erb

**Comment by coblej** [comment]
@jt112 You can just provide the content you want and David or I will implement it or, if you prefer, one of us can show you how to submit a pull request to update the code base with the desired content.

**Comment by jt112** [comment]
Please have an opinon about this.
![ddr](https://cloud.githubusercontent.com/assets/3597157/6112575/42d263d2-b05f-11e4-910e-affae24166d0.png)

**Comment by jt112** [comment]
Also, might you know how difficult it would be to pull in the standard footer?

![selection_002](https://cloud.githubusercontent.com/assets/3597157/6112745/438864ec-b060-11e4-8382-9d8d1ff76111.png)

**Comment by coblej** [comment]
With respect to the text, one suggestion would be to start the first paragraph with "The Duke Digital Repository (DDR) provides access ..." rather than just jumping in with an unexplained use of "DDR".  And I trust you to know better than I do what the appropriate thing to say about the license is.  My hunch is that the first things made available through the interface (the DataVis datasets) won't have the license you mention, since they will probably each have their own licenses.

**Comment by coblej** [comment]
With respect to pulling in the standard footer, if you mean that literally, my hunch is that the main complication will be a potential clash between the styles used in that footer and the Blacklight styles used in the repository application.  And I wonder a bit about the wisdom of including the "Drupal Sign-In" link in the footer of the repository application since it has nothing to do with Drupal.  It would certainly be possible to develop a footer that includes the same elements (more or less) as the library web site footer if that would be an acceptable substitute for including the library web site footer per se.

**Comment by dchandekstark** [comment]
Maybe we can just defer to Cory and Sean on this?

—D

David Chandek-Stark
Repository Developer
Duke University Libraries
david.chandek.stark@duke.edu<mailto:david.chandek.stark@duke.edu>
@dchandekstark



On Feb 9, 2015, at 2:52 PM, Jim Coble <notifications@github.com<mailto:notifications@github.com>> wrote:


With respect to pulling in the standard footer, if you mean that literally, my hunch is that the main complication will be a potential clash between the styles used in that footer and the Blacklight styles used in the repository application. And I wonder a bit about the wisdom of including the "Drupal Sign-In" link in the footer of the repository application since it has nothing to do with Drupal. It would certainly be possible to develop a footer that includes the same elements (more or less) as the library web site footer if that would be an acceptable substitute for including the library web site footer per se.
