### ISSUE TITLE
Add bookmark checkbox missing on some related items

### ISSUE THREAD

**Issue by corylown** [duke-libraries/ddr-public#414]
From test fest

Bookmark option displays on one related item but not the other.
<img width="287" alt="screen shot 2016-06-02 at 12 37 02 pm" src="https://cloud.githubusercontent.com/assets/458247/15758475/cbbf52e8-28d8-11e6-9e4f-3a8731b54593.png">
<img width="274" alt="screen shot 2016-06-02 at 12 37 16 pm" src="https://cloud.githubusercontent.com/assets/458247/15758479/ce88937c-28d8-11e6-9a4a-6a6fbf3aaffc.png">

**Comment by seanaery** [comment]
Seems this is happening periodically because the related items partial gets nested within the (7-day) cache block, so sometimes this would be cached with a checkbox and other times without. It's useful to be able to do `<%= render_document_index_with_view("gallery", docs) %>` as we're doing to get a consistent grid presentation there though, and useful to cache this part for performance impact. 

One easy way to address this is just to hide the rendered checkboxes in the Related Items section with CSS so they don't display to anyone even when they appear in the markup.
